baseURL = "https://www.christiankruep.com"
languageCode = "en"
defaultContentLanguage = "en"

theme = 'lynx'

enableEmoji = true

title = "Solvitur Ambulando"
copyright = "Ad astra per alia porci"

[params.author]
    name = "Christian Kruep"
    headline = "The Dude in the Arena"
    image = "images/headshot.jpeg"
    
    
    links = [
        { email = "mailto:christiankruep@me.com" },
        { linkedin = "https://www.linkedin.com/in/christiankruep/" },
        { github = "https://github.com/christiankruep" },
        { github = { href = "https://github.com/christiankruep/PersonalWebsite/blob/main/README.md", text = "Readme?" } },
        { link = { href = "https://www.peakbagger.com/climber/climber.aspx?cid=44836", text = "Peak Bagger" } },
        { link = {href = "https://www.kpig.com/", text = "Pure Pork" } },
        { flickr = "https://www.flickr.com/people/191698010@N03/" }
    ]
   

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"

    